export const CREDENTIALS_STORE = 'CREDENTIALS_STORE';
export const CREDENTIALS_UPDATE = 'CREDENTIALS_UPDATE';
export const CREDENTIALS_CLEAR = 'CREDENTIALS_CLEAR';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const RESTAURANT_DETAIL_REQUEST = 'RESTAURANT_DETAIL_REQUEST';
export const RESTAURANT_DETAIL_SUCCESS = 'RESTAURANT_DETAIL_SUCCESS';
export const RESTAURANT_DETAIL_FAILURE = 'RESTAURANT_DETAIL_FAILURE';