// RESERVATION STATUS
export const GET_PRINTERS_REQUEST = 'GET_PRINTERS_REQUEST';
export const GET_PRINTERS_SUCCESS = 'GET_PRINTERS_SUCCESS';
export const GET_PRINTERS_FAILURE = 'GET_PRINTERS_FAILURE';
export const GET_PRINTERS_CLEAR = 'GET_PRINTERS_CLEAR';