// src/database/schema.ts
import {appSchema, tableSchema} from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 17,
  tables: [
    tableSchema({
      name: 'orders',
      columns: [
        {name: 'order_id', type: 'string', isOptional: false},
        {name: 'order_no', type: 'string'},
        {name: 'location_id', type: 'string'},
        {name: 'customer_id', type: 'string'},
        {name: 'full_name', type: 'string'},
        {name: 'phone', type: 'string'},
        {name: 'email', type: 'string'},
        {name: 'order_type_id', type: 'string'},
        {name: 'order_type_group', type: 'string'},
        {name: 'order_source_name', type: 'string'},
        {name: 'order_date', type: 'string'},
        {name: 'order_time', type: 'string'},
        {name: 'order_total', type: 'number'},
        {name: 'status_id', type: 'string'},
        {name: 'table_id', type: 'string'},
        {name: 'table_names', type: 'string'},
        {name: 'is_paid', type: 'boolean'},
        {name: 'local_time', type: 'string'},
        {name: 'order_source', type: 'string'},
        {name: 'mh_transactions_entities', type: 'string'},
        {name: 'refund_status', type: 'string'},
        {name: 'order_totals', type: 'string'},
        {name: 'next_status', type: 'string'},
        {name: 'payment_failed', type: 'boolean'},
        {name: 'status', type: 'string'},
        {name: 'sort_order', type: 'number'},
        {name: 'order_source_detail', type: 'string'},
        {name: 'is_order_cancelled', type: 'boolean'},
        {name: 'payment_type', type: 'string'},
        {name: 'unique_id', type: 'string'},
        {name: 'is_tax_removed', type: 'number'},
        {name: 'is_schedule_order', type: 'boolean'},
        {name: 'current_formatted_date', type: 'string'},
        {name: 'order_type', type: 'string'},
        {name: 'is_scheduled', type: 'boolean'},
        {name: 'transactions_with_tip', type: 'string'},
        {name: 'cp_payment_tip_amount', type: 'number'},
        {name: 'is_customization_count_required', type: 'boolean'},
        {name: 'cash_info', type: 'string'},
        {name: 'custom_note', type: 'string'},
        {name: 'pre_authorized_card', type: 'string'},
        {name: 'kot_throttling_item_details', type: 'string'},
        {name: 'order_summary_items', type: 'string'},
        {name: 'hold_items', type: 'string'},
        {name: 'split_details', type: 'string'},
        {name: 'is_split_bill', type: 'boolean'},
        {name: 'split_id', type: 'string'},
        {name: 'open_cash_drawer', type: 'boolean'},
        {name: 'items', type: 'string'},
        {name: 'totals', type: 'string'},
        {name: 'payment_status', type: 'string'},
        {name: 'transactions', type: 'string'},
        {name: 'active_valets', type: 'string'},
        {name: 'delivery_staff_details', type: 'string'},
        {name: 'business_details', type: 'string'},
        {name: 'payment_link', type: 'string'},
        {name: 'item_tax', type: 'string'},
        {name: 'service_tax', type: 'string'},
        {name: 'is_payment_done', type: 'boolean'},
        {name: 'refunded_items', type: 'string'},
        {name: 'refunded_amount', type: 'string'},
        {name: 'voided_items', type: 'string'},
        {name: 'discount', type: 'number'},
        {name: 'discount_type', type: 'string'},
        {name: 'is_order_merged', type: 'boolean'},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
      ],
      primaryKey: 'order_id',
    }),
    tableSchema({
      name: 'order_dummies',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'dummy_text', type: 'string' },
        { name: 'dummy_value', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_totals',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'order_totals', type: 'string' },
        { name: 'item_tax', type: 'string' },
        { name: 'totals', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'order_items',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'item_id', type: 'string' },
        { name: 'item_name', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'price', type: 'number' },
        { name: 'subtotal', type: 'number' },
        { name: 'tax_fees', type: 'number' },
        { name: 'order_item_id', type: 'string' },
        { name: 'remaining_quantity', type: 'number' },
        { name: 'remaining_amount', type: 'number' },
        { name: 'void_reason', type: 'string' },
        { name: 'last_updated', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'synced_at', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'is_voided', type: 'boolean' },
        { name: 'voided_quantity', type: 'number' },
        { name: 'voided_amount', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'app_settings',
      columns: [
        { name: 'setting_key', type: 'string' },
        { name: 'setting_value', type: 'string' },
        { name: 'location_id', type: 'string' },
        { name: 'order_type', type: 'string' },
        { name: 'last_synced', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'restaurants',
      columns: [
        { name: 'restaurant_id', type: 'string' },
        { name: 'business_name', type: 'string' },
        { name: 'branch_name', type: 'string' },
        { name: 'location_id', type: 'string' },
        { name: 'staff_id', type: 'string' },
        { name: 'country', type: 'string' },
        { name: 'currency', type: 'string' },
        { name: 'timezone', type: 'string' },
        { name: 'pin_based_login', type: 'number' },
        { name: 'enabled_modules', type: 'string' },
        { name: 'order_types', type: 'string' },
        { name: 'third_parties', type: 'string' },
        { name: 'media', type: 'string' },
        { name: 'payment_provider', type: 'string' },
        { name: 'disabled_services', type: 'string' },
        { name: 'additional_print_space', type: 'number' },
        { name: 'cuisines', type: 'string' },
        { name: 'last_synced', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'printers',
      columns: [
        { name: 'device_id', type: 'string' },
        { name: 'device_identifier', type: 'string' },
        { name: 'device_name', type: 'string' },
        { name: 'device_type', type: 'string' },
        { name: 'model_name', type: 'string' },
        { name: 'ip_address', type: 'string' },
        // { name: 'is_default', type: 'boolean' },
        // { name: 'location_id', type: 'string' },
        { name: 'staff_id', type: 'string' },
        { name: 'last_synced', type: 'number' },
        // { name: 'created_at', type: 'number' },
        // { name: 'updated_at', type: 'number' },
        //
         { name: 'name', type: 'string' },
        { name: 'type', type: 'number' },
        { name: 'address', type: 'string' },
        { name: 'purpose', type: 'number' },

        { name: 'is_station_printer', type: 'boolean' },
        { name: 'is_58mm', type: 'boolean' },
        { name: 'is_star', type: 'boolean' },

        { name: 'is_default', type: 'number' },
        { name: 'is_active_dnd', type: 'boolean', isOptional: true },
        { name: 'is_print_to_update', type: 'boolean', isOptional: true },

        { name: 'model', type: 'string', isOptional: true },
        { name: 'print_to', type: 'string', isOptional: true },

        { name: 'device_id', type: 'string', isOptional: true },
        { name: 'merchant_id', type: 'string', isOptional: true },
        { name: 'location_id', type: 'string', isOptional: true },
        { name: 'tab_identifier', type: 'string', isOptional: true },

        { name: 'printer_port', type: 'string', isOptional: true },
        { name: 'attribute_name', type: 'string', isOptional: true },

        { name: 'cuisine_id', type: 'string', isOptional: true },
        { name: 'cuisine_ids', type: 'string', isOptional: true },
        { name: 'cuisine_tag_names', type: 'string', isOptional: true },
        { name: 'selected_cuisines', type: 'string', isOptional: true },

        { name: 'station_name', type: 'string', isOptional: true },
        { name: 'nick_name', type: 'string', isOptional: true },
        { name: 'magil_print_id', type: 'string', isOptional: true },

        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});

export default schema;